/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.NhanVienDAO;
import com.qlks3tl.Model.NhanVien;
import com.qlks3tl.utils.Auth;
import com.qlks3tl.utils.MsgBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_DangNhap_taikhoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Dangnhap_matkhau = new javax.swing.JPasswordField();
        btn_DangNhap_Thoat = new javax.swing.JButton();
        btn_DangNhap_dangnhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tài Khoản");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 92, 35));

        txt_DangNhap_taikhoan.setBackground(new java.awt.Color(99, 99, 198));
        txt_DangNhap_taikhoan.setForeground(new java.awt.Color(255, 255, 255));
        txt_DangNhap_taikhoan.setText("NVQL");
        txt_DangNhap_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DangNhap_taikhoanActionPerformed(evt);
            }
        });
        jPanel2.add(txt_DangNhap_taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 338, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mật Khẩu");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 92, -1));

        txt_Dangnhap_matkhau.setBackground(new java.awt.Color(99, 99, 198));
        txt_Dangnhap_matkhau.setForeground(new java.awt.Color(255, 255, 255));
        txt_Dangnhap_matkhau.setText("123");
        jPanel2.add(txt_Dangnhap_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 338, -1));

        btn_DangNhap_Thoat.setBackground(new java.awt.Color(99, 99, 198));
        btn_DangNhap_Thoat.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_DangNhap_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_DangNhap_Thoat.setText("Thoát");
        btn_DangNhap_Thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_DangNhap_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhap_ThoatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_DangNhap_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 180, 55));

        btn_DangNhap_dangnhap.setBackground(new java.awt.Color(99, 99, 198));
        btn_DangNhap_dangnhap.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_DangNhap_dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_DangNhap_dangnhap.setText("Đăng Nhập");
        btn_DangNhap_dangnhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_DangNhap_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhap_dangnhapActionPerformed(evt);
            }
        });
        jPanel2.add(btn_DangNhap_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 180, 55));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/anenn22.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 500, 460));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangNhap_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhap_ThoatActionPerformed
        // TODO add your handling code here:
        ketThuc();
    }//GEN-LAST:event_btn_DangNhap_ThoatActionPerformed

    private void btn_DangNhap_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhap_dangnhapActionPerformed
        // TODO add your handling code here:
        dangNhap();
    }//GEN-LAST:event_btn_DangNhap_dangnhapActionPerformed

    private void txt_DangNhap_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DangNhap_taikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DangNhap_taikhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangNhap_Thoat;
    private javax.swing.JButton btn_DangNhap_dangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_DangNhap_taikhoan;
    private javax.swing.JPasswordField txt_Dangnhap_matkhau;
    // End of variables declaration//GEN-END:variables

   
    private void init(){
        this.setLocationRelativeTo(null);
        
    }
     NhanVienDAO dao = new NhanVienDAO();
     public static String Tenhienthi;
     public static String maNVlayhienthi;
    void dangNhap() {
        String tk = txt_DangNhap_taikhoan.getText();
        String matKhau = txt_Dangnhap_matkhau.getText();
        NhanVien epl = dao.selectebyID(tk);
        if (epl == null) {
            JOptionPane.showMessageDialog(this, "Wrong username!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!matKhau.equals(epl.getmKhau())) {
            JOptionPane.showMessageDialog(this, "Wrong password!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Auth.user = epl;
            MsgBox.alert(this, "Login successfully!");
            Tenhienthi = epl.getTenNV();
            maNVlayhienthi= epl.getMaNV();
         //   System.out.println(maNVlayhienthi);
            this.dispose();
            frm_manhinhchinh ld = new frm_manhinhchinh();
            ld.setVisible(true);
        }
    }
    
    void ketThuc(){
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }
}
