/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.KhachHangDAO;
import com.qlks3tl.DAO.PhieuDangKiDAO;
import com.qlks3tl.DAO.PhongDAO;
import com.qlks3tl.Model.KhachHang;
import com.qlks3tl.Model.PhieuDangKi;
import com.qlks3tl.Model.Phong;
import com.qlks3tl.utils.MsgBox;
import java.awt.print.PrinterException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Acer
 */
public class frm_DatPhong extends javax.swing.JFrame {

    /**
     * Creates new form frm_DatPhong
     */
    public frm_DatPhong() {
        initComponents();
        init();
        txt_frmDatPhong_SoPhong.setEditable(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_frmDatPhong_TenKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_frmDatPhong_GioRa = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        lbl_frmDatPhong_GiaNgay = new javax.swing.JLabel();
        lbl_frmDatPhong_GiaGio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_frmDatPhong_SoNgayo = new javax.swing.JLabel();
        lbl_frmDatPhong_SoGioo = new javax.swing.JLabel();
        lbl_frmDatPhong_TongTien = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txt_frmDatPhong_GioVao = new com.toedter.calendar.JDateChooser();
        txt_GioVao = new javax.swing.JTextField();
        txt_GioRa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txt_frmDatPhong_SDT = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_frmDatPhong_CMND = new javax.swing.JTextField();
        txt_frmDatPhong_SoPhong = new javax.swing.JTextField();
        pnl_InVe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_indatphong = new javax.swing.JTextArea();
        btn_DatPhong_Xem = new javax.swing.JButton();
        btn_DatPhong_In = new javax.swing.JButton();
        btn_DatPhong_GuiMail = new javax.swing.JButton();
        btn_PhieuDK_xacnhan = new javax.swing.JButton();
        btn_Phieudk_huybo = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("ĐẶT PHÒNG");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 99, 198));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tên KH");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 99, 198));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Số Phòng");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(99, 99, 198));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Giờ Ra");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(99, 99, 198));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Giá Phòng");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_frmDatPhong_GiaNgay.setBackground(new java.awt.Color(255, 255, 255));
        lbl_frmDatPhong_GiaNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_frmDatPhong_GiaNgay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_frmDatPhong_GiaNgay.setText("Giá Ngày");
        lbl_frmDatPhong_GiaNgay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_frmDatPhong_GiaGio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_frmDatPhong_GiaGio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_frmDatPhong_GiaGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_frmDatPhong_GiaGio.setText("Giá Giờ");
        lbl_frmDatPhong_GiaGio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(99, 99, 198));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Số Ngày");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(99, 99, 198));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Số Giờ");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_frmDatPhong_SoNgayo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_frmDatPhong_SoNgayo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_frmDatPhong_SoNgayo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_frmDatPhong_SoNgayo.setText("Số Lượng");
        lbl_frmDatPhong_SoNgayo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_frmDatPhong_SoGioo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_frmDatPhong_SoGioo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_frmDatPhong_SoGioo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_frmDatPhong_SoGioo.setText("Số Lượng");
        lbl_frmDatPhong_SoGioo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_frmDatPhong_TongTien.setBackground(new java.awt.Color(255, 255, 255));
        lbl_frmDatPhong_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_frmDatPhong_TongTien.setForeground(new java.awt.Color(99, 99, 198));
        lbl_frmDatPhong_TongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_frmDatPhong_TongTien.setText("Tổng Tiền Phòng");
        lbl_frmDatPhong_TongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(99, 99, 198));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Giờ Nhận Phòng");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        txt_GioVao.setText("11:00");
        txt_GioVao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GioVaoActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(99, 99, 198));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SĐT");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(99, 99, 198));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Tổng Tiền Phòng");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(99, 99, 198));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CMND");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_frmDatPhong_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_frmDatPhong_CMND, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txt_frmDatPhong_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txt_frmDatPhong_SoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_frmDatPhong_SoGioo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_frmDatPhong_SoNgayo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_frmDatPhong_GiaNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_frmDatPhong_GiaGio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator2)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_frmDatPhong_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_frmDatPhong_GioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_GioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_frmDatPhong_GioRa, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_GioRa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_frmDatPhong_GiaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_frmDatPhong_GiaGio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_frmDatPhong_TenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_frmDatPhong_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt_frmDatPhong_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_frmDatPhong_SoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_frmDatPhong_SoNgayo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_frmDatPhong_SoGioo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_frmDatPhong_GioRa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(txt_GioRa))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_frmDatPhong_GioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_GioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_frmDatPhong_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        txt_indatphong.setColumns(20);
        txt_indatphong.setRows(5);
        jScrollPane1.setViewportView(txt_indatphong);

        btn_DatPhong_Xem.setBackground(new java.awt.Color(99, 99, 198));
        btn_DatPhong_Xem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_DatPhong_Xem.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatPhong_Xem.setText("XEM TRƯỚC");
        btn_DatPhong_Xem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_DatPhong_Xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhong_XemActionPerformed(evt);
            }
        });

        btn_DatPhong_In.setBackground(new java.awt.Color(99, 99, 198));
        btn_DatPhong_In.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_DatPhong_In.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatPhong_In.setText("IN PHIẾU");
        btn_DatPhong_In.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_DatPhong_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhong_InActionPerformed(evt);
            }
        });

        btn_DatPhong_GuiMail.setBackground(new java.awt.Color(99, 99, 198));
        btn_DatPhong_GuiMail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_DatPhong_GuiMail.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatPhong_GuiMail.setText("GỬI MAIL");
        btn_DatPhong_GuiMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_DatPhong_GuiMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhong_GuiMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_InVeLayout = new javax.swing.GroupLayout(pnl_InVe);
        pnl_InVe.setLayout(pnl_InVeLayout);
        pnl_InVeLayout.setHorizontalGroup(
            pnl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_InVeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                    .addGroup(pnl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_DatPhong_In, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_DatPhong_GuiMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_DatPhong_Xem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        pnl_InVeLayout.setVerticalGroup(
            pnl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(pnl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_InVeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_InVeLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGroup(pnl_InVeLayout.createSequentialGroup()
                            .addComponent(btn_DatPhong_Xem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_DatPhong_In, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_DatPhong_GuiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        btn_PhieuDK_xacnhan.setBackground(new java.awt.Color(99, 99, 198));
        btn_PhieuDK_xacnhan.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_PhieuDK_xacnhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_PhieuDK_xacnhan.setText("XÁC NHẬN");
        btn_PhieuDK_xacnhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_PhieuDK_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhieuDK_xacnhanActionPerformed(evt);
            }
        });

        btn_Phieudk_huybo.setBackground(new java.awt.Color(249, 32, 1));
        btn_Phieudk_huybo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_Phieudk_huybo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Phieudk_huybo.setText("HỦY BỎ");
        btn_Phieudk_huybo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_Phieudk_huybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Phieudk_huyboActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(99, 99, 198));
        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setText("CẬP NHẬT");
        btn_CapNhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_InVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_PhieuDK_xacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Phieudk_huybo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Phieudk_huybo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_PhieuDK_xacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_InVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DatPhong_XemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhong_XemActionPerformed
       
        inPhieuDatPhong();
        {
        btn_DatPhong_In.setEnabled(true);
        btn_DatPhong_GuiMail.setEnabled(false);
        btn_DatPhong_Xem.setEnabled(false);
        }
        
        
        
    }//GEN-LAST:event_btn_DatPhong_XemActionPerformed

    private void btn_DatPhong_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhong_InActionPerformed
        
        
        try {
            txt_indatphong.print();
            MsgBox.alert(this, "In thành công");
             {
        btn_DatPhong_In.setEnabled(false);
        btn_DatPhong_GuiMail.setEnabled(true);
        btn_DatPhong_Xem.setEnabled(false);
        }
            
        } catch (PrinterException e) {
            Logger.getLogger(frm_ChiTietHoaDon.class.getName()).log(Level.SEVERE, null,e);
        }
    }//GEN-LAST:event_btn_DatPhong_InActionPerformed

    private void btn_DatPhong_GuiMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhong_GuiMailActionPerformed
        // TODO add your handling code here:
        {
        btn_DatPhong_In.setEnabled(false);
        btn_DatPhong_GuiMail.setEnabled(false);
        btn_DatPhong_Xem.setEnabled(false);
       GuiMail gui= new GuiMail();
        gui.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_DatPhong_GuiMailActionPerformed

    private void btn_PhieuDK_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhieuDK_xacnhanActionPerformed
        // TODO add your handling code here:
        pnl_InVe.setVisible(true);
        KhachHang kh = getFormKhachHang();
        PhieuDangKi pdk = getFormPDK();
        if (kiemTra()){
        try {
            if(khDAO.selectebyID(kh.getCMND())== null){
                khDAO.insert(kh);
            }
            pdkDAO.insert(pdk);
            System.out.println(pdk.getMaPDK());
            MsgBox.alert(this, "Đặt phòng thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Đặt phòng thất bại!!");
        }
        }
    }//GEN-LAST:event_btn_PhieuDK_xacnhanActionPerformed

    private void btn_Phieudk_huyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Phieudk_huyboActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_Phieudk_huyboActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
        tinhngay();
        if(kiemTra()){
            System.out.println("mypackage.UI.frm_DatPhong.btn_CapNhatActionPerformed()");
        } else {
            System.out.println("sai");
        }
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void txt_GioVaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GioVaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GioVaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_DatPhong().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_DatPhong_GuiMail;
    private javax.swing.JButton btn_DatPhong_In;
    private javax.swing.JButton btn_DatPhong_Xem;
    private javax.swing.JButton btn_PhieuDK_xacnhan;
    private javax.swing.JButton btn_Phieudk_huybo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_frmDatPhong_GiaGio;
    private javax.swing.JLabel lbl_frmDatPhong_GiaNgay;
    private javax.swing.JLabel lbl_frmDatPhong_SoGioo;
    private javax.swing.JLabel lbl_frmDatPhong_SoNgayo;
    private javax.swing.JLabel lbl_frmDatPhong_TongTien;
    private javax.swing.JPanel pnl_InVe;
    private javax.swing.JTextField txt_GioRa;
    private javax.swing.JTextField txt_GioVao;
    private javax.swing.JTextField txt_frmDatPhong_CMND;
    private com.toedter.calendar.JDateChooser txt_frmDatPhong_GioRa;
    private com.toedter.calendar.JDateChooser txt_frmDatPhong_GioVao;
    private javax.swing.JTextField txt_frmDatPhong_SDT;
    private javax.swing.JTextField txt_frmDatPhong_SoPhong;
    private javax.swing.JTextField txt_frmDatPhong_TenKH;
    private javax.swing.JTextArea txt_indatphong;
    // End of variables declaration//GEN-END:variables

    void init(){
        // set trang thai panel in ve va nut
        btn_DatPhong_In.setEnabled(false);
        btn_DatPhong_GuiMail.setEnabled(false);
        btn_DatPhong_Xem.setEnabled(true);
        pnl_InVe.setVisible(false);
        
        setLocationRelativeTo(null);
        /// 
        
        
    }
    PhongDAO pDAO = new PhongDAO();
    PhieuDangKiDAO pdkDAO = new PhieuDangKiDAO();
    KhachHangDAO khDAO = new KhachHangDAO();
void inPhieuDatPhong(){
    
    
    txt_indatphong.append("\t PHIEU DAT PHONG KHACH SAN 3TL \n\n");
    
    txt_indatphong.append("MaPhieuDangKy: "+  pdkDAO.selectebySP(txt_frmDatPhong_SoPhong.getText()).getMaPDK() +"\n");
    txt_indatphong.append("Ten Khach Hang: "+txt_frmDatPhong_TenKH.getText()+"  \n");
    
    txt_indatphong.append("So Dien Thoai: "+txt_frmDatPhong_SDT.getText() +" \n");
    txt_indatphong.append("So Phong: "+txt_frmDatPhong_SoPhong.getText() +" \n");
    txt_indatphong.append("Ngay bat dau : "+ txt_GioVao.getText()+" Giờ  "+ date.format(txt_frmDatPhong_GioVao.getDate()) +" \n");
    txt_indatphong.append("Ngay ket thuc : "+ txt_GioRa.getText()+" Giờ  "+ date.format(txt_frmDatPhong_GioRa.getDate()) + "\n");
    
    txt_indatphong.setEditable(false);
}
void setForm(Phong p){
    lbl_frmDatPhong_GiaGio.setText(String.valueOf((pDAO.selectebyID(p.getSoPhong())).getGiaPhong_Gio()));
    lbl_frmDatPhong_GiaNgay.setText(String.valueOf((pDAO.selectebyID(p.getSoPhong())).getGiaPhong_Ngay()));
    txt_frmDatPhong_SoPhong.setText(String.valueOf(p.getSoPhong()));
}
PhieuDangKi getFormPDK(){
    int songay1 =(int) (songay*24 + tongsogio) ;
    PhieuDangKi pdk = new PhieuDangKi();
    pdk.setTenKH(txt_frmDatPhong_CMND.getText());
    pdk.setSoPhong(txt_frmDatPhong_SoPhong.getText());
    pdk.setNgayDK(txt_frmDatPhong_GioVao.getDate());
    pdk.setNgayTra(txt_frmDatPhong_GioRa.getDate());
    pdk.setGioVao(txt_GioVao.getText());
    pdk.setGioRa(txt_GioRa.getText());
    pdk.setSoNgay(songay1);
    pdk.setTinhTrangCho(1);
    return pdk;
}
KhachHang getFormKhachHang(){
    KhachHang kh =new KhachHang();
    kh.setCMND(txt_frmDatPhong_CMND.getText());
    kh.setTenKH(txt_frmDatPhong_TenKH.getText());
    kh.setSDT(txt_frmDatPhong_SDT.getText());
    return kh;
}
    public static DateFormat dateAHour = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    public static DateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    public static DateFormat hour = new SimpleDateFormat("HH:mm");
    public double tongsogio;
    public double songay;
    Date datevao = new Date();
    Date datera = new Date();
    void tinhngay( ) {
    
        String a = date.format(txt_frmDatPhong_GioVao.getDate());
        String b = txt_GioVao.getText();
        String a2 = date.format(txt_frmDatPhong_GioRa.getDate());
        String b2 = txt_GioRa.getText();
        System.out.println(a+" "+b);
           try {            
               datevao = dateAHour.parse(a+" "+b);
               datera = dateAHour.parse(a2+" "+b2);
           } catch (ParseException ex) {
               System.out.println("mypackage.UI.frm_ChitietPhong.tinhngay()");
           }
           double t1 = (datera.getTime()-datevao.getTime())%(24*60*60*1000);
           tongsogio = Math.ceil(t1/(60*60*1000));
           songay = (datera.getTime()-datevao.getTime())/(24*60*60*1000);
           System.out.println(tongsogio);
           System.out.println(songay);
        lbl_frmDatPhong_SoNgayo.setText(String.valueOf(songay)+" Ngày");
        lbl_frmDatPhong_SoGioo.setText(String.valueOf(tongsogio)+" Giờ");
        //boolean aaa = ((datevao.getTime()) - (datera.getTime()))>0;
    }
    
    boolean kiemTra(){
        List<PhieuDangKi> list = new List<PhieuDangKi>() {
            @Override
            public int size() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean isEmpty() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean contains(Object o) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Iterator<PhieuDangKi> iterator() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object[] toArray() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public <T> T[] toArray(T[] a) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean add(PhieuDangKi e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean remove(Object o) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean containsAll(Collection<?> c) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean addAll(Collection<? extends PhieuDangKi> c) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean addAll(int index, Collection<? extends PhieuDangKi> c) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean removeAll(Collection<?> c) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public boolean retainAll(Collection<?> c) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void clear() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public PhieuDangKi get(int index) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public PhieuDangKi set(int index, PhieuDangKi element) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void add(int index, PhieuDangKi element) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public PhieuDangKi remove(int index) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int indexOf(Object o) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int lastIndexOf(Object o) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public ListIterator<PhieuDangKi> listIterator() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public ListIterator<PhieuDangKi> listIterator(int index) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public List<PhieuDangKi> subList(int fromIndex, int toIndex) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        list =pdkDAO.selectbySql("SELECT * FROM Phieu_DK WHERE SoPhong = ?", txt_frmDatPhong_SoPhong.getText()); 
        Date datevaoNow = new Date();
        Date dateraNow = new Date();
        String ngayVao = date.format(txt_frmDatPhong_GioVao.getDate());
        String GioVao = txt_GioVao.getText();
        String ngayRa = date.format(txt_frmDatPhong_GioRa.getDate());
        String gioRa = txt_GioRa.getText();
        try {            
               datevaoNow = dateAHour.parse(ngayVao+" "+GioVao);
               dateraNow = dateAHour.parse(ngayRa+" "+gioRa);
           } catch (ParseException ex) {
               System.out.println("mypackage.UI.frm_ChitietPhong.tinhngay()");
           }
        for (PhieuDangKi phieuDangKi : list) {
            System.out.println(phieuDangKi);
            Date datevao = new Date();
            Date datera = new Date();
            String a = date.format(phieuDangKi.getNgayDK());
            String b = phieuDangKi.getGioRa();
            String a2 = date.format(phieuDangKi.getNgayTra());
            String b2 = phieuDangKi.getGioRa();
            System.out.println("aaaaaaaaaaaaa");
                try {            
                    datevao = dateAHour.parse(a+" "+b);
                    System.out.println(datevao);
                    datera = dateAHour.parse(a2+" "+b2);
                    System.out.println(datera);
                } catch (ParseException ex) {
                    System.out.println("mypackage.UI.frm_ChitietPhong.tinhngay()");
                }
        //boolean aaa = ((datevao.getTime()) - (datera.getTime()))>0;
             if(!(datevaoNow.getTime() < datevao.getTime() || datevaoNow.getTime() > datera.getTime())){
                 MsgBox.alert(this, "kiểm tra lại thời gian đặt phòng ");
                 return false;
             }if(!(dateraNow.getTime() < datevao.getTime() || dateraNow.getTime() > datera.getTime())){
                 MsgBox.alert(this, "kiểm tra lại thời gian đặt phòng ");
                 return false;
             }
        }
        if (txt_frmDatPhong_TenKH.getText().equals("") || txt_frmDatPhong_CMND.getText().equals("")
                || txt_frmDatPhong_SDT.getText().equals("")) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ thông tin Khách Hàng ");
            return false;

        } else if (!txt_frmDatPhong_SDT.getText().matches("0[0-9\\s.-]{9,10}")) {
            MsgBox.alert(this, "Số điện thoại không đúng");
            return false;
        } else if (!txt_frmDatPhong_CMND.getText().matches("[0-9]{9,15}")) {
            MsgBox.alert(this, "CMND không đúng");
            return false;
        }
        if(datera.getTime()>datevao.getTime()){
            MsgBox.alert(this, "Ngày vào phải nhỏ hơn ngày trả");
            return false;
        }
        return true;
    }

}
