/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.HoaDonDAO;
import com.qlks3tl.DAO.KhachHangDAO;
import com.qlks3tl.DAO.PhieuDangKiDAO;
import com.qlks3tl.DAO.PhongDAO;
import com.qlks3tl.Model.HoaDon;
import com.qlks3tl.Model.KhachHang;
import com.qlks3tl.Model.PhieuDangKi;
import com.qlks3tl.Model.Phong;
import com.qlks3tl.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import static java.lang.System.exit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Acer
 */
public class frm_ChitietPhong extends javax.swing.JFrame {

    /**
     * Creates new form frm_ChitietPhong
     */
   public static frm_ChitietPhong instance;

    public frm_ChitietPhong() {
        initComponents();
        instance = this;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_ChitietPhong_TenKH = new javax.swing.JTextField();
        txt_ChitietPhong_SoPhong = new javax.swing.JTextField();
        txt_ChitietPhong_giovao = new com.toedter.calendar.JDateChooser();
        txt_ChitietPhong_giora = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txt_ChitietPhong_LoaiPhong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_ChitietPhong_CMND = new javax.swing.JTextField();
        txt_GioDK = new javax.swing.JTextField();
        txt_GioTra = new javax.swing.JTextField();
        lbl_ChiTietPhong_TongTienPhong = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        btn_ChiTietPhong_HuyBo = new javax.swing.JButton();
        btn_ChiTietPhong_ThanhToan = new javax.swing.JButton();
        btn_ChiTietPhong_CapNhat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_ChiTietPhong_Songay = new javax.swing.JLabel();
        lbl_ChiTietPhong_SoGio = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_ChiTietPhong_GiaNgay = new javax.swing.JLabel();
        lbl_ChiTietPhong_GiaGio = new javax.swing.JLabel();
        btn_DatPhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("CHI TIẾT PHÒNG");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 99, 198));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tên KH");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 99, 198));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Số Phòng");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(99, 99, 198));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Giờ vào ");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(99, 99, 198));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Giờ Ra");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(99, 99, 198));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Loại Phòng");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(99, 99, 198));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CMND");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        txt_ChitietPhong_CMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ChitietPhong_CMNDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_ChitietPhong_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_ChitietPhong_SoPhong))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_ChitietPhong_giora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_ChitietPhong_giovao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_GioDK)
                                .addComponent(txt_GioTra))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ChitietPhong_LoaiPhong)))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_ChitietPhong_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ChitietPhong_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ChitietPhong_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ChitietPhong_SoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ChitietPhong_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ChitietPhong_giovao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_GioDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChitietPhong_giora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GioTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        lbl_ChiTietPhong_TongTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ChiTietPhong_TongTienPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ChiTietPhong_TongTienPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChiTietPhong_TongTienPhong.setText("Tổng Tiền Phòng");
        lbl_ChiTietPhong_TongTienPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(99, 99, 198));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tổng Tiền Phòng");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        btn_ChiTietPhong_HuyBo.setBackground(new java.awt.Color(249, 32, 1));
        btn_ChiTietPhong_HuyBo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_ChiTietPhong_HuyBo.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChiTietPhong_HuyBo.setText("HỦY BỎ");
        btn_ChiTietPhong_HuyBo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_ChiTietPhong_HuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietPhong_HuyBoActionPerformed(evt);
            }
        });

        btn_ChiTietPhong_ThanhToan.setBackground(new java.awt.Color(0, 204, 51));
        btn_ChiTietPhong_ThanhToan.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_ChiTietPhong_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChiTietPhong_ThanhToan.setText("THANH TOÁN");
        btn_ChiTietPhong_ThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_ChiTietPhong_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietPhong_ThanhToanActionPerformed(evt);
            }
        });

        btn_ChiTietPhong_CapNhat.setBackground(new java.awt.Color(99, 99, 198));
        btn_ChiTietPhong_CapNhat.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_ChiTietPhong_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChiTietPhong_CapNhat.setText("CẬP NHẬT");
        btn_ChiTietPhong_CapNhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_ChiTietPhong_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietPhong_CapNhatActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(99, 99, 198));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Số Ngày");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(99, 99, 198));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Số Giờ");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_ChiTietPhong_Songay.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ChiTietPhong_Songay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ChiTietPhong_Songay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChiTietPhong_Songay.setText("Số Lượng");
        lbl_ChiTietPhong_Songay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_ChiTietPhong_SoGio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ChiTietPhong_SoGio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ChiTietPhong_SoGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChiTietPhong_SoGio.setText("Số Lượng");
        lbl_ChiTietPhong_SoGio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(99, 99, 198));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Giá Phòng");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_ChiTietPhong_GiaNgay.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ChiTietPhong_GiaNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ChiTietPhong_GiaNgay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChiTietPhong_GiaNgay.setText("Giá Ngày");
        lbl_ChiTietPhong_GiaNgay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        lbl_ChiTietPhong_GiaGio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ChiTietPhong_GiaGio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ChiTietPhong_GiaGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChiTietPhong_GiaGio.setText("Giá Giờ");
        lbl_ChiTietPhong_GiaGio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(lbl_ChiTietPhong_SoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ChiTietPhong_GiaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_ChiTietPhong_GiaGio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ChiTietPhong_Songay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ChiTietPhong_GiaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ChiTietPhong_GiaGio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ChiTietPhong_Songay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ChiTietPhong_SoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        btn_DatPhong.setBackground(new java.awt.Color(99, 99, 198));
        btn_DatPhong.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_DatPhong.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatPhong.setText("ĐẶT PHÒNG");
        btn_DatPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ChiTietPhong_TongTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 343, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_ChiTietPhong_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ChiTietPhong_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ChiTietPhong_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChiTietPhong_TongTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ChiTietPhong_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ChiTietPhong_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ChiTietPhong_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChiTietPhong_HuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietPhong_HuyBoActionPerformed
      
        dispose();
    }//GEN-LAST:event_btn_ChiTietPhong_HuyBoActionPerformed

    private void btn_ChiTietPhong_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietPhong_ThanhToanActionPerformed
        PhieuDangKi pdk = pdkDAO.selectebySP_FalseTTHoaDOn(txt_ChitietPhong_SoPhong.getText());
      //  System.out.println(pdk.getSoPhong()+ pdk.getTinhTrangHoaDon());
        HoaDon hd = geFormHoaDon(pdk);
        Phong phong = new Phong();
      if(kiemtra()){
          try {
               hdDAO.insert(hd);
               MsgBox.alert(this, "Thanh Toán Thành Công!");
                phong = phdao1.selectebyID(hd.getSoPhong());
                phong.setTrangthai(null);
                pdk.setTinhTrangHoaDon(1);
                
                phdao1.update(phong);
                pdkDAO.updatepdkchothanhtoan(pdk);
                dispose();
           } catch (Exception e) {
               MsgBox.alert(this, "Thanh Toán Thất Bại!!!");
                e.printStackTrace();
           }
      }
        
    }//GEN-LAST:event_btn_ChiTietPhong_ThanhToanActionPerformed

    private void btn_ChiTietPhong_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietPhong_CapNhatActionPerformed
        // TODO add your handling code here:
        if(kiemtra()){
            update();
        }
    }//GEN-LAST:event_btn_ChiTietPhong_CapNhatActionPerformed

    private void txt_ChitietPhong_CMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ChitietPhong_CMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ChitietPhong_CMNDActionPerformed

    private void btn_DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhongActionPerformed
        frm_DatPhong npl = new frm_DatPhong();
        Phong p = new Phong();
        p = phdao1.selectebyID(txt_ChitietPhong_SoPhong.getText());
        npl.setVisible(true);
        npl.setForm(p);
        dispose();
    }//GEN-LAST:event_btn_DatPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ChitietPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ChitietPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ChitietPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ChitietPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ChitietPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChiTietPhong_CapNhat;
    private javax.swing.JButton btn_ChiTietPhong_HuyBo;
    private javax.swing.JButton btn_ChiTietPhong_ThanhToan;
    private javax.swing.JButton btn_DatPhong;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_ChiTietPhong_GiaGio;
    private javax.swing.JLabel lbl_ChiTietPhong_GiaNgay;
    private javax.swing.JLabel lbl_ChiTietPhong_SoGio;
    private javax.swing.JLabel lbl_ChiTietPhong_Songay;
    private javax.swing.JLabel lbl_ChiTietPhong_TongTienPhong;
    private javax.swing.JTextField txt_ChitietPhong_CMND;
    private javax.swing.JTextField txt_ChitietPhong_LoaiPhong;
    private javax.swing.JTextField txt_ChitietPhong_SoPhong;
    private javax.swing.JTextField txt_ChitietPhong_TenKH;
    private com.toedter.calendar.JDateChooser txt_ChitietPhong_giora;
    private com.toedter.calendar.JDateChooser txt_ChitietPhong_giovao;
    private javax.swing.JTextField txt_GioDK;
    private javax.swing.JTextField txt_GioTra;
    // End of variables declaration//GEN-END:variables
void init() {
        this.setLocationRelativeTo(null);
        //  jPanel3.setVisible(false);
        setlocktypedata();

    }

    KhachHangDAO khDAO = new KhachHangDAO();
    PhieuDangKiDAO pdkDAO = new PhieuDangKiDAO();
    PhongDAO phdao1 = new PhongDAO();
    HoaDonDAO hdDAO = new HoaDonDAO();

    void setForm(Phong nv, PhieuDangKi pdk1) {
        txt_ChitietPhong_SoPhong.setText(nv.getSoPhong());
        txt_ChitietPhong_LoaiPhong.setText(nv.getMaLoaiPhong());
        lbl_ChiTietPhong_GiaGio.setText(String.valueOf(nv.getGiaPhong_Gio()) + "/H");
        lbl_ChiTietPhong_GiaNgay.setText(String.valueOf(nv.getGiaPhong_Ngay()) + "/N");
        txt_ChitietPhong_TenKH.setText((khDAO.selectebyID(pdk1.getTenKH())).getTenKH());
        txt_ChitietPhong_CMND.setText(pdk1.getTenKH());
        txt_ChitietPhong_giovao.setDate(pdk1.getNgayDK());
        txt_GioDK.setText(pdk1.getGioVao());
        txt_GioTra.setText(pdk1.getGioRa());
        txt_ChitietPhong_giora.setDate(pdk1.getNgayTra());
       

        tinhngay(pdk1);
        lbl_ChiTietPhong_Songay.setText(String.valueOf(songay) + " Ngày");
        lbl_ChiTietPhong_SoGio.setText(String.valueOf(tongsogio) + " Giờ");
        double tongtien;
        tongtien = (tongsogio) * phdao1.selectebyID(pdk1.getSoPhong()).getGiaPhong_Ngay();
        if(tongsogio > 4){
            tongtien = (songay +1) * phdao1.selectebyID(pdk1.getSoPhong()).getGiaPhong_Ngay();
        } else {
            tongtien = (tongsogio) * phdao1.selectebyID(pdk1.getSoPhong()).getGiaPhong_Gio() + songay*(phdao1.selectebyID(pdk1.getSoPhong()).getGiaPhong_Ngay());
        }
        lbl_ChiTietPhong_TongTienPhong.setText(String.valueOf(tongtien) + "00" );

    }
// void setFormCoKHtuPDK (PhieuDangKi pdk){
//     txt_ChitietPhong_TenKH.setText(pdk.getTenKH());
//     txt_ChitietPhong_giovao.setDate(pdk.getNgayDK());
//     txt_ChitietPhong_giora.setDate(pdk.getNgayTra());
//     
//     
// }
    //double tongTienDV = txt_ChiTietPhong_SoLuongDV * (dvk.getGia());
    double tongtien;
    void setFormtuPDK(PhieuDangKi pdk2) {
        txt_ChitietPhong_giovao.setDate(pdk2.getNgayDK());
        txt_ChitietPhong_giora.setDate(pdk2.getNgayTra());
        txt_GioDK.setText(pdk2.getGioVao());
        txt_GioTra.setText(pdk2.getGioRa());
        tinhngay(pdk2);
        lbl_ChiTietPhong_Songay.setText(String.valueOf(songay) + " Ngày");
        lbl_ChiTietPhong_SoGio.setText(String.valueOf(tongsogio) + " Giờ");
        
        lbl_ChiTietPhong_TongTienPhong.setText(String.valueOf(tongtien) + "00" );
        setlocktypedata();
        

    }
    

    public void setlocktypedata() {
        // set type data
        txt_ChitietPhong_LoaiPhong.setBackground(new Color(99, 99, 198));
        txt_ChitietPhong_LoaiPhong.setFont(new Font("SansSe rif", Font.BOLD, 14));

        txt_ChitietPhong_SoPhong.setBackground(new Color(99, 99, 198));
        txt_ChitietPhong_SoPhong.setFont(new Font("SansSe rif", Font.BOLD, 14));

        txt_ChitietPhong_TenKH.setBackground(new Color(99, 99, 198));
        txt_ChitietPhong_TenKH.setFont(new Font("SansSe rif", Font.BOLD, 14));

        txt_ChitietPhong_giovao.setEnabled(false);
        txt_ChitietPhong_TenKH.setEnabled(false);
        txt_ChitietPhong_CMND.setEnabled(false);
        txt_ChitietPhong_LoaiPhong.setEnabled(false);
        txt_ChitietPhong_SoPhong.setEnabled(false);
    }
    public static DateFormat dateAHour = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    public static DateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    public static DateFormat hour = new SimpleDateFormat("HH:mm");
    public double tongsogio;
    public double songay;
    void tinhngay( PhieuDangKi pdk) {
        Date datevao = new Date();
        Date datera = new Date();
        String a = date.format(pdk.getNgayDK());
        String b = pdk.getGioVao();
        String a2 = date.format(txt_ChitietPhong_giora.getDate());
        String b2 = txt_GioTra.getText();
        System.out.println(a+" "+b);
        
           try {            
               datevao = dateAHour.parse(a+" "+b);
               datera = dateAHour.parse(a2+" "+b2);
           } catch (ParseException ex) {
               System.out.println("mypackage.UI.frm_ChitietPhong.tinhngay()");
           }
           double t1 = (datera.getTime()-datevao.getTime())%(24*60*60*1000);
           tongsogio = Math.ceil(t1/(60*60*1000));
           songay = (datera.getTime()-datevao.getTime())/(24*60*60*1000);
           System.out.println(tongsogio);
           System.out.println(songay);
           tongtien = (tongsogio) * phdao1.selectebyID(pdk.getSoPhong()).getGiaPhong_Ngay();
                if(tongsogio > 4){
                    tongtien = (songay +1) * phdao1.selectebyID(pdk.getSoPhong()).getGiaPhong_Ngay();
                } else {
                    tongtien = (tongsogio) * phdao1.selectebyID(pdk.getSoPhong()).getGiaPhong_Gio() + songay*(phdao1.selectebyID(pdk.getSoPhong()).getGiaPhong_Ngay());
            }
    }

    PhieuDangKi getForm() {
        PhieuDangKi nv = new PhieuDangKi();
//        System.out.println("dsdsd " + pdkDAO.selectbyMAPDK(nv.getMaPDK()) );
        
        int songay1 =(int)(songay*24 + tongsogio) ;
        nv.setTenKH(txt_ChitietPhong_TenKH.getText());
        nv.setSoPhong(txt_ChitietPhong_SoPhong.getText());
        nv.setLoaiPhong(txt_ChitietPhong_LoaiPhong.getText());
        nv.setNgayDK(txt_ChitietPhong_giovao.getDate());
        nv.setNgayTra(txt_ChitietPhong_giora.getDate());
        nv.setGioRa(txt_GioTra.getText());
        nv.setGioVao(txt_GioDK.getText());
        nv.setSoNgay(songay1);
       
        return nv;
    }
    HoaDon geFormHoaDon(PhieuDangKi pdk){
        HoaDon hd = new HoaDon();
        List<HoaDon> listHD = hdDAO.selectAll();
        int i = listHD.size()+1;
        hd.setMaHD("HD"+i);
        hd.setMaNV(DangNhap.maNVlayhienthi);
        hd.setCMND(txt_ChitietPhong_CMND.getText());
        hd.setMaPDK(pdk.getMaPDK());
        hd.setNgayTao(pdk.getNgayDK());
        hd.setTongTien(Double.parseDouble(lbl_ChiTietPhong_TongTienPhong.getText()));
        hd.setSoPhong(pdk.getSoPhong());
        hd.setSoNgay(pdk.getSoNgay());
        System.out.println(hd.getCMND());        
        System.out.println(hd.getMaPDK());
        System.out.println(hd.getNgayTao());
        System.out.println(hd.getSoPhong());
        System.out.println(hd.getTongTien());        
        System.out.println(hd.getMaHD());


        return hd;
    }
//     void getFormxx(PhieuDangKi pdk) {
//        
//        
//        System.out.println("dsdsd223 " +pdk.getMaPDK());
//        
//        int songay1 =(int)(songay*24 + tongsogio) ;
//        pdk.setTenKH(txt_ChitietPhong_TenKH.getText());
//        pdk.setSoPhong(txt_ChitietPhong_SoPhong.getText());
//        pdk.setLoaiPhong(txt_ChitietPhong_LoaiPhong.getText());
//        pdk.setNgayDK(txt_ChitietPhong_giovao.getDate());
//        pdk.setNgayTra(txt_ChitietPhong_giora.getDate());
//        pdk.setGioRa(txt_GioTra.getText());
//        pdk.setGioVao(txt_GioDK.getText());
//        pdk.setSoNgay(songay1);
//
//        
//    }
    void update() {
        
         PhieuDangKi pdk = getForm();
//        System.out.println("mã pdk"+ pdk.getMaPDK());
//         System.out.println("mã pdk lúc get form " + pdkDAO.selectbyMAPDK(pdk.getMaPDK()) );
//        pdkDAO.selectebyID(pdk.getMaPDK()+"");
         tinhngay(pdk);
  //      System.out.println("AA"+pdk.getSoNgay());
       
         //  System.out.println(pdk.getSoPhong());
       //     System.out.println(pdk.getMaPDK());
       
       try {

//                pdk = pdkDAO.selectebyID(pdk.getSoPhong());
//                pdkDAO.update(pdk);
          
            pdkDAO.update22(pdk);
            
           
            System.out.println(pdk.getMaPDK()+ " ma pdk lúc đã update ?");
            setFormtuPDK(pdk);
            MsgBox.alert(this, "Cập nhật thành công!");
            //         System.out.println(pdk.getSoPhong());

            //  System.out.println("đã thêm vào ");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Cập nhật thất bại");
        }

    }

    boolean kiemtra(){
        tinhngay(pdkDAO.selectebySP_FalseTTHoaDOn(txt_ChitietPhong_SoPhong.getText()));
        if(tongtien < 0){
            MsgBox.alert(this, "Thời gian trả phòng phải lớn hơn thời gian vào ");
            return false;
            
        }
        return true;
    }
}
