/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.PhieuDangKiDAO;
import com.qlks3tl.DAO.PhongDAO;
import com.qlks3tl.Model.PhieuDangKi;
import com.qlks3tl.Model.Phong;
import com.qlks3tl.utils.Auth;
import com.qlks3tl.utils.MsgBox;
import com.qlks3tl.utils.getinfo;
import java.awt.Color;
import java.awt.Font;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.Timer;
import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;

/**
 *
 * @author Acer
 */
public class frm_manhinhchinh extends javax.swing.JFrame {

    private JPanel childPanel;
    private JButton btn_CheckClickMenu = new JButton();
    private int sizeBorder = 0;
    
    

    public frm_manhinhchinh() {
        initComponents();
        init();
       // btn_MHN_ThongKe.setVisible(false);
      //  System.out.println(MainPanel.getSize());
        //  ChuyenDoiPanel controller = new ChuyenDoiPanel(MainPanel);

        //  controller.setView(pnl_NhanVien, btnDichVu1);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_MHC_TenHienThi = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        panelBorder1 = new com.qlks3tl.swing.PanelBorder();
        btn_MHN_ThongKe = new javax.swing.JButton();
        btn_MHN_SoDoPhong = new javax.swing.JButton();
        btnDanhSachDP = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btn_MHN_NhanVien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_MHN_HoaDon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_MHN_ThongKe1 = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(150, 196, 200));

        jPanel2.setBackground(new java.awt.Color(150, 196, 200));

        jLabel1.setBackground(new java.awt.Color(150, 196, 200));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/1-2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOTEL - 3TL");

        lbl_MHC_TenHienThi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_MHC_TenHienThi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MHC_TenHienThi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_MHC_TenHienThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8_user_28px_1.png"))); // NOI18N
        lbl_MHC_TenHienThi.setText("Tên Nhân Vien");

        lbldongho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldongho.setForeground(new java.awt.Color(255, 255, 255));
        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8_time_28px.png"))); // NOI18N
        lbldongho.setText("Đồng hồ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(lbl_MHC_TenHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldongho)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldongho)
                    .addComponent(lbl_MHC_TenHienThi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBorder1.setBackground(new java.awt.Color(150, 196, 200));

        btn_MHN_ThongKe.setBackground(new java.awt.Color(150, 196, 200));
        btn_MHN_ThongKe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_MHN_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_ThongKe.png"))); // NOI18N
        btn_MHN_ThongKe.setText("Thống kê");
        btn_MHN_ThongKe.setContentAreaFilled(false);
        btn_MHN_ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MHN_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_MHN_ThongKe.setOpaque(true);
        btn_MHN_ThongKe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKeMouseMoved(evt);
            }
        });
        btn_MHN_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKeMouseExited(evt);
            }
        });
        btn_MHN_ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MHN_ThongKeActionPerformed(evt);
            }
        });

        btn_MHN_SoDoPhong.setBackground(new java.awt.Color(150, 196, 200));
        btn_MHN_SoDoPhong.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_MHN_SoDoPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Phong.png"))); // NOI18N
        btn_MHN_SoDoPhong.setText("Sơ đồ phòng");
        btn_MHN_SoDoPhong.setContentAreaFilled(false);
        btn_MHN_SoDoPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MHN_SoDoPhong.setDisabledIcon(null);
        btn_MHN_SoDoPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_MHN_SoDoPhong.setOpaque(true);
        btn_MHN_SoDoPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_MHN_SoDoPhongMouseMoved(evt);
            }
        });
        btn_MHN_SoDoPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MHN_SoDoPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MHN_SoDoPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MHN_SoDoPhongMouseExited(evt);
            }
        });
        btn_MHN_SoDoPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MHN_SoDoPhongActionPerformed(evt);
            }
        });

        btnDanhSachDP.setBackground(new java.awt.Color(150, 196, 200));
        btnDanhSachDP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDanhSachDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_HoaDon.png"))); // NOI18N
        btnDanhSachDP.setText("DS  phòng");
        btnDanhSachDP.setContentAreaFilled(false);
        btnDanhSachDP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDanhSachDP.setDisabledIcon(null);
        btnDanhSachDP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDanhSachDP.setOpaque(true);
        btnDanhSachDP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDanhSachDPMouseMoved(evt);
            }
        });
        btnDanhSachDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDanhSachDPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDanhSachDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDanhSachDPMouseExited(evt);
            }
        });
        btnDanhSachDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachDPActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(150, 196, 200));
        btnKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_KhachHang.png"))); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setContentAreaFilled(false);
        btnKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhachHang.setDisabledIcon(null);
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setOpaque(true);
        btnKhachHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseMoved(evt);
            }
        });
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseExited(evt);
            }
        });
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btn_MHN_NhanVien.setBackground(new java.awt.Color(150, 196, 200));
        btn_MHN_NhanVien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_MHN_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_NhanVien.png"))); // NOI18N
        btn_MHN_NhanVien.setText("Nhân viên");
        btn_MHN_NhanVien.setContentAreaFilled(false);
        btn_MHN_NhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MHN_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_MHN_NhanVien.setOpaque(true);
        btn_MHN_NhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_MHN_NhanVienMouseMoved(evt);
            }
        });
        btn_MHN_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MHN_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MHN_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MHN_NhanVienMouseExited(evt);
            }
        });
        btn_MHN_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MHN_NhanVienActionPerformed(evt);
            }
        });

        btn_MHN_HoaDon.setBackground(new java.awt.Color(150, 196, 200));
        btn_MHN_HoaDon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_MHN_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_HoaDon.png"))); // NOI18N
        btn_MHN_HoaDon.setText("Hóa đơn");
        btn_MHN_HoaDon.setContentAreaFilled(false);
        btn_MHN_HoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MHN_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_MHN_HoaDon.setOpaque(true);
        btn_MHN_HoaDon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_MHN_HoaDonMouseMoved(evt);
            }
        });
        btn_MHN_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MHN_HoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MHN_HoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MHN_HoaDonMouseExited(evt);
            }
        });
        btn_MHN_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MHN_HoaDonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(150, 196, 200));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_CheckIn.png"))); // NOI18N
        jLabel4.setText("Checkin đặt trước");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        btn_MHN_ThongKe1.setBackground(new java.awt.Color(150, 196, 200));
        btn_MHN_ThongKe1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_MHN_ThongKe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Cong.png"))); // NOI18N
        btn_MHN_ThongKe1.setText("Checkin Phòng");
        btn_MHN_ThongKe1.setContentAreaFilled(false);
        btn_MHN_ThongKe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MHN_ThongKe1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_MHN_ThongKe1.setOpaque(true);
        btn_MHN_ThongKe1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKe1MouseMoved(evt);
            }
        });
        btn_MHN_ThongKe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKe1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKe1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MHN_ThongKe1MouseExited(evt);
            }
        });
        btn_MHN_ThongKe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MHN_ThongKe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDanhSachDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_MHN_SoDoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_MHN_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_MHN_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_MHN_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(btn_MHN_ThongKe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MHN_SoDoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDanhSachDP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_MHN_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_MHN_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_MHN_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_MHN_ThongKe1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(150, 196, 200));
        MainPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MHN_SoDoPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_SoDoPhongMouseMoved
        /*btnDatPhong.setBackground(Color.decode("#DA81F5"));*/
    }//GEN-LAST:event_btn_MHN_SoDoPhongMouseMoved

    private void btn_MHN_SoDoPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_SoDoPhongMouseClicked
        hoverMenu(btn_MHN_SoDoPhong, 0);
    }//GEN-LAST:event_btn_MHN_SoDoPhongMouseClicked

    private void btn_MHN_SoDoPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MHN_SoDoPhongActionPerformed
        this.btn_CheckClickMenu = btn_MHN_SoDoPhong;
        this.sizeBorder = 0;
        hoverMenu(btn_MHN_SoDoPhong, 0);
        MainPanel.removeAll();
        childPanel = new pnl_SoDoPhong();
        

        MainPanel.add(childPanel);
        MainPanel.validate();
    }//GEN-LAST:event_btn_MHN_SoDoPhongActionPerformed

    private void btnKhachHangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseMoved

    }//GEN-LAST:event_btnKhachHangMouseMoved

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked

    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        this.btn_CheckClickMenu = btnKhachHang;
        this.sizeBorder = 0;
        hoverMenu(btnKhachHang, 0);
        MainPanel.removeAll();
        childPanel = new pnl_KhachHang();

        MainPanel.getAccessibleContext();
        MainPanel.add(childPanel);
        MainPanel.validate();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btn_MHN_NhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_NhanVienMouseMoved

    }//GEN-LAST:event_btn_MHN_NhanVienMouseMoved

    private void btn_MHN_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_NhanVienMouseClicked

    }//GEN-LAST:event_btn_MHN_NhanVienMouseClicked

    private void btn_MHN_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MHN_NhanVienActionPerformed
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền truy cập ");
        } else{
        this.btn_CheckClickMenu = btn_MHN_NhanVien;
        this.sizeBorder = 0;
        hoverMenu(btn_MHN_NhanVien, 0);
        MainPanel.removeAll();

        childPanel = new pnl_NhanVien();

        MainPanel.getAccessibleContext();
        MainPanel.add(childPanel);
        MainPanel.validate();
}
    }//GEN-LAST:event_btn_MHN_NhanVienActionPerformed

    private void btn_MHN_ThongKeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKeMouseMoved

    }//GEN-LAST:event_btn_MHN_ThongKeMouseMoved

    private void btn_MHN_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKeMouseClicked

    }//GEN-LAST:event_btn_MHN_ThongKeMouseClicked

    private void btn_MHN_ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKeActionPerformed

        this.btn_CheckClickMenu = btn_MHN_ThongKe;
        this.sizeBorder = 0;
        hoverMenu(btn_MHN_ThongKe,0);
        MainPanel.removeAll();
         if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền truy cập ");
        } else{
        childPanel = new pnl_ThongKe();

        MainPanel.getAccessibleContext();
        MainPanel.add(childPanel);

        MainPanel.validate();
        }
    }//GEN-LAST:event_btn_MHN_ThongKeActionPerformed

    private void btnDanhSachDPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachDPMouseMoved

    }//GEN-LAST:event_btnDanhSachDPMouseMoved

    private void btnDanhSachDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachDPMouseClicked

    }//GEN-LAST:event_btnDanhSachDPMouseClicked

    private void btnDanhSachDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachDPActionPerformed
        this.btn_CheckClickMenu = btnDanhSachDP;
        this.sizeBorder = 0;
        hoverMenu(btnDanhSachDP, 0);
        MainPanel.removeAll();
        childPanel = new pnl_Dsphong();

        MainPanel.getAccessibleContext();
        MainPanel.add(childPanel);

        MainPanel.validate();
    }//GEN-LAST:event_btnDanhSachDPActionPerformed

    private void btn_MHN_SoDoPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_SoDoPhongMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_MHN_SoDoPhong, 0);
    }//GEN-LAST:event_btn_MHN_SoDoPhongMouseEntered

    private void btnDanhSachDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachDPMouseEntered
        // TODO add your handling code here:
        hoverMenu(btnDanhSachDP, 0);
    }//GEN-LAST:event_btnDanhSachDPMouseEntered

    private void btnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseEntered
        // TODO add your handling code here:
        hoverMenu(btnKhachHang, 0);
    }//GEN-LAST:event_btnKhachHangMouseEntered

    private void btn_MHN_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_NhanVienMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_MHN_NhanVien, 0);

    }//GEN-LAST:event_btn_MHN_NhanVienMouseEntered

    private void btn_MHN_ThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKeMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_MHN_ThongKe, 0);
    }//GEN-LAST:event_btn_MHN_ThongKeMouseEntered

    private void btn_MHN_SoDoPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_SoDoPhongMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_MHN_SoDoPhongMouseExited

    private void btnDanhSachDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachDPMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btnDanhSachDPMouseExited

    private void btnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btnKhachHangMouseExited

    private void btn_MHN_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_NhanVienMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_MHN_NhanVienMouseExited

    private void btn_MHN_ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKeMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_MHN_ThongKeMouseExited

    private void btn_MHN_HoaDonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_HoaDonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MHN_HoaDonMouseMoved

    private void btn_MHN_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_HoaDonMouseClicked
        hoverMenu(btn_MHN_HoaDon, 0);
    }//GEN-LAST:event_btn_MHN_HoaDonMouseClicked

    private void btn_MHN_HoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_HoaDonMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_MHN_HoaDon, 0);
    }//GEN-LAST:event_btn_MHN_HoaDonMouseEntered

    private void btn_MHN_HoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_HoaDonMouseExited
        setColorMenuItem();
    }//GEN-LAST:event_btn_MHN_HoaDonMouseExited

    private void btn_MHN_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MHN_HoaDonActionPerformed
       this.btn_CheckClickMenu = btn_MHN_HoaDon;
        this.sizeBorder = 0;
        hoverMenu(btn_MHN_HoaDon, 0);
        MainPanel.removeAll();
        childPanel = new pnl_HoaDon();

        MainPanel.getAccessibleContext();
        MainPanel.add(childPanel);

        MainPanel.validate();
    }//GEN-LAST:event_btn_MHN_HoaDonActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
         JFileChooser jFileChooser = new JFileChooser("E:\\SUMER2022\\test hinh anh report");
          jFileChooser.showOpenDialog(this);
      //  File imageFile = new File("E:\\testNB\\test111\\Untitled.png");
       File imageFile = jFileChooser.getSelectedFile();
            imageFile.getAbsolutePath();
     
       
       
       
        ITesseract instance = new Tesseract(); 
        instance.setDatapath("E:\\SUMER2022\\Tess4J-3.4.8-src\\Tess4J\\tessdata");
        System.err.println(instance.getClass().getName().toString());
        try {
            String result = instance.doOCR(imageFile);
        //    System.out.println(result);
//             String[] splits = result.split("-");
//            for (String item : splits)
//            System.out.println(item);
            
            // System.out.println(result.indexOf("MaPhieuDangKy:"));
           // System.out.println(result.indexOf("Ten Khach Hang:"));
           
          //  System.out.println(result.indexOf("So Phong:"));
          //  System.out.println(result.indexOf("Ngay bat dau :"));
          //  System.out.println(result.indexOf("Ngay ket thuc :"));
           String mapdk = result.substring(45,47);
           int mapdk3= Integer.parseInt(mapdk);
           
           getinfo.getmapdk= mapdk;
           System.out.println(result.substring(45,47));
           PhieuDangKiDAO pdkdao= new PhieuDangKiDAO();
           
           PhieuDangKi pdk= new  PhieuDangKi();
           Phong phong= new Phong();
           PhongDAO phdao= new PhongDAO();
           
            frm_XacNhanDangKyPhong xacnhandkp = new frm_XacNhanDangKyPhong();
           xacnhandkp.setVisible(true);
            pdk = pdkdao.selectbyMAPDK(mapdk3);
            
            
            System.out.println(pdk);
            
            
            xacnhandkp.setForm(phdao.selectebyID(pdk.getSoPhong()),pdk);
            
            
            // select string  , mapdk int
           // int a= Integer.valueOf(mapdk);
           // String.valueOf(a);
           
            
           
            
            
           // String ten =result.substring(46, 61);
           // String sdt =result.substring(77,87);
          
           // System.out.println(result.substring(77,87));
           // System.out.println(result.substring(98,101));
          //  System.out.println(result.substring(117,127));
          //  System.out.println(result.substring(144));
            
          //  result.substring(61,80);
    
            
 
        } catch (TesseractException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setBackground(Color.decode("#6363C6"));
        jLabel4.setBorder(BorderFactory.createLineBorder(new Color(150, 196, 200), 3));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void btn_MHN_ThongKe1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKe1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MHN_ThongKe1MouseMoved

    private void btn_MHN_ThongKe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKe1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MHN_ThongKe1MouseClicked

    private void btn_MHN_ThongKe1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKe1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MHN_ThongKe1MouseEntered

    private void btn_MHN_ThongKe1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKe1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MHN_ThongKe1MouseExited

    private void btn_MHN_ThongKe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MHN_ThongKe1ActionPerformed
        // TODO add your handling code here:
        CheckinDatTruocbangdulieu ckindattrc = new CheckinDatTruocbangdulieu();
        ckindattrc.setVisible(true);
   
    }//GEN-LAST:event_btn_MHN_ThongKe1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_manhinhchinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnDanhSachDP;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btn_MHN_HoaDon;
    private javax.swing.JButton btn_MHN_NhanVien;
    private javax.swing.JButton btn_MHN_SoDoPhong;
    private javax.swing.JButton btn_MHN_ThongKe;
    private javax.swing.JButton btn_MHN_ThongKe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_MHC_TenHienThi;
    private javax.swing.JLabel lbldongho;
    private com.qlks3tl.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);

        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lbldongho.setText(text);
                
            }
        }).start();
        
        lbl_MHC_TenHienThi.setFont(new Font("SansSe rif", Font.BOLD, 19));
        lbl_MHC_TenHienThi.setText(DangNhap.Tenhienthi);
        childPanel = new pnl_SoDoPhong();
        MainPanel.add(childPanel);
        
       // jLabel1.setSize(145, 70);
    }

    private void setColorMenuItem() {
        // set color button
        btn_MHN_SoDoPhong.setBackground(new Color(150, 196, 200));
        btnDanhSachDP.setBackground(new Color(150, 196, 200));
        btnKhachHang.setBackground(new Color(150, 196, 200));
        btn_MHN_NhanVien.setBackground(new Color(150, 196, 200));
        btn_MHN_ThongKe.setBackground(new Color(150, 196, 200));
        btn_MHN_HoaDon.setBackground(new Color(150, 196, 200));
        jLabel4.setBackground(new Color(150, 196, 200));
        this.btn_CheckClickMenu.setBackground(Color.decode("#6363C6"));

        // set color border
    }

    private void hoverMenu(JButton btn, int sizeMatteBorder) {
        this.btn_CheckClickMenu.setBackground(Color.decode("#6363C6"));
        // set color button
        btn.setBackground(Color.decode("#6363C6"));

    }
    

}
