/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.HoaDonDAO;
import com.qlks3tl.Model.KhachHang;
import com.qlks3tl.DAO.KhachHangDAO;
import com.qlks3tl.Model.HoaDon;
import com.qlks3tl.utils.Auth;
import com.qlks3tl.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Acer
 */
public class pnl_KhachHang extends javax.swing.JPanel {

    public pnl_KhachHang() {
        initComponents();
        //  setOpaque(false);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_KhachHang_Ten = new javax.swing.JTextField();
        txt_KhachHang_CMND = new javax.swing.JTextField();
        txt_KhachHang_SDT = new javax.swing.JTextField();
        txt_KhachHang_DOB = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Khachhang_them = new javax.swing.JButton();
        btn_Khachhang_sua = new javax.swing.JButton();
        btn_Khachhang_xoa = new javax.swing.JButton();
        btn_Khachhang_new = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_KhachHang_TimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KhachHang_KhachHang = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_KhackHang_show = new javax.swing.JTable();

        setBackground(new java.awt.Color(150, 196, 200));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(168, 222, 247)));
        setPreferredSize(new java.awt.Dimension(908, 683));

        jPanel1.setBackground(new java.awt.Color(150, 196, 200));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("KHÁCH HÀNG");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        jPanel2.setBackground(new java.awt.Color(150, 196, 200));

        txt_KhachHang_Ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KhachHang_TenActionPerformed(evt);
            }
        });

        txt_KhachHang_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KhachHang_SDTActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 99, 198));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tên ");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 99, 198));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CMND");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(99, 99, 198));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SDT");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(99, 99, 198));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DOB");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        btn_Khachhang_them.setBackground(new java.awt.Color(99, 99, 198));
        btn_Khachhang_them.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_Khachhang_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Khachhang_them.setText("THÊM");
        btn_Khachhang_them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_Khachhang_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Khachhang_themActionPerformed(evt);
            }
        });

        btn_Khachhang_sua.setBackground(new java.awt.Color(99, 99, 198));
        btn_Khachhang_sua.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_Khachhang_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Khachhang_sua.setText("SỬA");
        btn_Khachhang_sua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_Khachhang_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Khachhang_suaActionPerformed(evt);
            }
        });

        btn_Khachhang_xoa.setBackground(new java.awt.Color(99, 99, 198));
        btn_Khachhang_xoa.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_Khachhang_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Khachhang_xoa.setText("XÓA");
        btn_Khachhang_xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_Khachhang_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Khachhang_xoaActionPerformed(evt);
            }
        });

        btn_Khachhang_new.setBackground(new java.awt.Color(99, 99, 198));
        btn_Khachhang_new.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_Khachhang_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_Khachhang_new.setText("MỚI");
        btn_Khachhang_new.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_Khachhang_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Khachhang_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Khachhang_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Khachhang_them, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Khachhang_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Khachhang_new, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_KhachHang_CMND, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KhachHang_SDT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KhachHang_DOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txt_KhachHang_Ten))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KhachHang_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KhachHang_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_KhachHang_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txt_KhachHang_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Khachhang_them, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Khachhang_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Khachhang_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Khachhang_new, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(150, 196, 200));

        txt_KhachHang_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_KhachHang_TimKiemKeyReleased(evt);
            }
        });

        tbl_KhachHang_KhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(168, 222, 247), 4, true));
        tbl_KhachHang_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_KhachHang_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên KH", "SDT", "CMND", "DOB"
            }
        ));
        tbl_KhachHang_KhachHang.setGridColor(new java.awt.Color(150, 196, 200));
        tbl_KhachHang_KhachHang.setRowHeight(27);
        tbl_KhachHang_KhachHang.setRowMargin(3);
        tbl_KhachHang_KhachHang.setSelectionBackground(new java.awt.Color(150, 196, 200));
        tbl_KhachHang_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachHang_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KhachHang_KhachHang);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(99, 99, 198));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tìm Kiếm");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_KhachHang_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_KhachHang_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_KhackHang_show.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 222, 247), 3));
        tbl_KhackHang_show.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_KhackHang_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên Khách Hàng", "CMND", "SĐT", "Loại Phòng", "Số Phòng", "Tổng tiền", "Ngày Checkin", "Ngày Checkout", "Tổng số Giờ"
            }
        ));
        tbl_KhackHang_show.setGridColor(new java.awt.Color(150, 196, 200));
        tbl_KhackHang_show.setRowHeight(27);
        tbl_KhackHang_show.setRowMargin(3);
        tbl_KhackHang_show.setSelectionBackground(new java.awt.Color(150, 196, 200));
        jScrollPane2.setViewportView(tbl_KhackHang_show);
        if (tbl_KhackHang_show.getColumnModel().getColumnCount() > 0) {
            tbl_KhackHang_show.getColumnModel().getColumn(0).setMinWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_KhachHang_TenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KhachHang_TenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KhachHang_TenActionPerformed

    private void txt_KhachHang_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KhachHang_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KhachHang_SDTActionPerformed

    private void btn_Khachhang_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Khachhang_themActionPerformed
        insert();
    }//GEN-LAST:event_btn_Khachhang_themActionPerformed

    private void btn_Khachhang_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Khachhang_suaActionPerformed
        update();
    }//GEN-LAST:event_btn_Khachhang_suaActionPerformed

    private void btn_Khachhang_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Khachhang_xoaActionPerformed
        delete();
    }//GEN-LAST:event_btn_Khachhang_xoaActionPerformed

    private void btn_Khachhang_xoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Khachhang_xoa1ActionPerformed
        //  clearForm();
    }//GEN-LAST:event_btn_Khachhang_xoa1ActionPerformed

    private void tbl_KhachHang_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachHang_KhachHangMouseClicked

        if (evt.getClickCount() == 1) {
            this.row = tbl_KhachHang_KhachHang.getSelectedRow();
            this.edit();
            FillTalbleToForm();
            filltablekhachhang_lichsu();

        }
    }//GEN-LAST:event_tbl_KhachHang_KhachHangMouseClicked

    private void btn_Khachhang_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Khachhang_newActionPerformed

        clearForm();// TODO add your handling code here:
    }//GEN-LAST:event_btn_Khachhang_newActionPerformed

    private void txt_KhachHang_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_KhachHang_TimKiemKeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_txt_KhachHang_TimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Khachhang_new;
    private javax.swing.JButton btn_Khachhang_sua;
    private javax.swing.JButton btn_Khachhang_them;
    private javax.swing.JButton btn_Khachhang_xoa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_KhachHang_KhachHang;
    private javax.swing.JTable tbl_KhackHang_show;
    private javax.swing.JTextField txt_KhachHang_CMND;
    private com.toedter.calendar.JDateChooser txt_KhachHang_DOB;
    private javax.swing.JTextField txt_KhachHang_SDT;
    private javax.swing.JTextField txt_KhachHang_Ten;
    private javax.swing.JTextField txt_KhachHang_TimKiem;
    // End of variables declaration//GEN-END:variables

    void init() {
        initComponents();
        this.fillTable();
        this.updateStatus();
        designTable();

    }
    KhachHangDAO khdao = new KhachHangDAO();
    int row = -1;

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_KhachHang_KhachHang.getModel();
        model.setRowCount(0);
// xóa tất cả các hàng trên table 
        try {
            List<KhachHang> list = khdao.selectAll(); // Lấy tất cả dữ liệu từ SQL 
            for (KhachHang kh : list) {
                Object[] row = {
                    // theo thu tu Database
                    kh.getTenKH(), kh.getSDT(), kh.getCMND(), kh.getDOB()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void setForm(KhachHang kh) {
        txt_KhachHang_Ten.setText(kh.getTenKH());
        txt_KhachHang_SDT.setText(kh.getSDT());
        txt_KhachHang_CMND.setText(kh.getCMND());
        txt_KhachHang_DOB.setDate(kh.getDOB());
    }

    KhachHang getForm() {
        KhachHang kh = new KhachHang();
        kh.setTenKH(txt_KhachHang_Ten.getText());
        kh.setSDT(txt_KhachHang_SDT.getText());
        kh.setCMND(txt_KhachHang_CMND.getText());
        kh.setDOB(txt_KhachHang_DOB.getDate());
        return kh;
    }

    void clearForm() {
        KhachHang kh = new KhachHang();
        this.setForm(kh);
        this.row = -1;
        this.updateStatus();
        fillTable();
    }

    void edit() {
        if (row != -1) {
            String CMND = (String) tbl_KhachHang_KhachHang.getValueAt(this.row, 2);

            tbl_KhachHang_KhachHang.setRowSelectionInterval(row, row);
            KhachHang kh = khdao.selectebyID(CMND);
            this.setForm(kh);
           
            this.updateStatus();
        }

    }

    void update() {
        if (kiemtra()) {
            KhachHang kh = getForm();

            try {
                khdao.update(kh);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại");
            }
        }
    }

    void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa Khách Hàng");
        } else {
            String CMND = txt_KhachHang_CMND.getText();
            if (MsgBox.confirm(this, "Bạn thực sự muốn xóa Khách Hàng này")) {
                try {
                    khdao.delete(CMND);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa thành công");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại");
                }
            }
        }
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);

        boolean first = (this.row == 0);
        boolean last = (this.row == (tbl_KhachHang_KhachHang.getRowCount() - 1));

        // Trạng thái form
        txt_KhachHang_CMND.setEditable(!edit);
        btn_Khachhang_them.setEnabled(!edit);
        btn_Khachhang_sua.setEnabled(edit);
        btn_Khachhang_xoa.setEnabled(edit);

    }

    void insert() {
        if (kiemtra()) {
            KhachHang kh = getForm();

            try {
                khdao.insert(kh);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại");
            }
        }
    }

    boolean kiemtra() {
        KhachHang kh = this.getForm();
        Calendar instance = Calendar.getInstance();
        int yearNow = instance.get(Calendar.YEAR);
        Date dateNow = java.util.Calendar.getInstance().getTime();
        Date date = txt_KhachHang_DOB.getDate();
        double year = ((dateNow.getTime() - date.getTime()) / (24 * 60 * 60 * 1000)) / 365;

        if (kh.getTenKH().equals("") || kh.getCMND().equals("")
                || kh.getSDT().equals("") || kh.getDOB().equals("")) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ thông tin Khách Hàng ");
            return false;

        } else if (!kh.getSDT().matches("0[0-9\\s.-]{9,10}")) {
            MsgBox.alert(this, "Số điện thoại không đúng");
            return false;
        } else if (!kh.getCMND().matches("[0-9]{9,15}")) {
            MsgBox.alert(this, "CMND không đúng");
            return false;
        } else if (year < 18) {
            MsgBox.alert(this, "Khách hàng chưa đủ 18 tuổi, vui lòng kiểm tra lại!!");
            return false;

        }
        return true;
    }

    void FillTalbleToForm() {
        List<KhachHang> list = khdao.selectAll();
        setForm(list.get(row));

    }

    // tim kiem theo CMND
    private void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tbl_KhachHang_KhachHang.getModel();
        model.setRowCount(0);

        String keyword = txt_KhachHang_TimKiem.getText();
        List<KhachHang> list = khdao.search(keyword);
        for (KhachHang nt : list) {
            model.addRow(new Object[]{
                nt.getTenKH(),
                nt.getSDT(),
                nt.getCMND(),
                nt.getDOB()
            });
        }
    }

    void designTable() {
        tbl_KhachHang_KhachHang.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        tbl_KhachHang_KhachHang.getTableHeader().setForeground(Color.BLACK);
        
        tbl_KhackHang_show.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        tbl_KhackHang_show.getTableHeader().setForeground(Color.BLACK);

    }
    HoaDonDAO hddao = new HoaDonDAO();

    void filltablekhachhang_lichsu() {
        
        DefaultTableModel model = (DefaultTableModel) tbl_KhackHang_show.getModel();
        model.setRowCount(0);
        try {

            String cmnd = txt_KhachHang_CMND.getText();
            System.out.println(cmnd);
            List<Object[]> list = hddao.getMaKHvaDaThanhtoan(cmnd);
            try {
                
           
            for (Object[] row : list) {
                Object[] r = {
                    row[0], row[1], row[2], row[3], row[4],(double)row[5],(Date) row[6], (Date) row[7],(int)row[8]
                };

                model.addRow(r);

            }
             } catch (Exception e) {
                 e.printStackTrace();
            }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
//       DefaultTableModel model = (DefaultTableModel) tbl_KhackHang_show.getModel();
//        model.setRowCount(0);
//        String cmnd = (txt_KhachHang_CMND.getText());
//// xóa tất cả các hàng trên table 
//        try {
//            List<KhachHang> list = khdao.selectbySql(cmnd); // Lấy tất cả dữ liệu từ SQL 
//            for (KhachHang kh : list) {
//                Object[] row = {
//                    // theo thu tu Database
//                    kh.getTenKH(), kh.getSDT(), kh.getCMND(), kh.getDOB()
//                };
//                model.addRow(row);
//            }
//        } catch (Exception e) {
//            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
//        }
     }

}
