/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.PhieuDangKiDAO;
import com.qlks3tl.DAO.PhongDAO;

import com.qlks3tl.Model.PhieuDangKi;
import com.qlks3tl.Model.Phong;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Acer
 */
public class pnl_SoDoPhong extends javax.swing.JPanel {

    /**
     * Creates new form pnl_SoDoPhong
     */
    PhongDAO phDAO = new PhongDAO();
    PhieuDangKiDAO pdkdao2 = new PhieuDangKiDAO();
    int a;

    public pnl_SoDoPhong() {
        initComponents();
        List<Phong> listP = phDAO.selectAll();
        List<PhieuDangKi> listpdk = pdkdao2.selectAll();
        addToPanelAccMana(listP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnl_showlistPhong = new javax.swing.JPanel();

        setBackground(new java.awt.Color(150, 196, 200));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(168, 222, 247)));
        setPreferredSize(new java.awt.Dimension(908, 683));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(150, 196, 200));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("SƠ ĐỒ PHÒNG");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        pnl_showlistPhong.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(pnl_showlistPhong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl_showlistPhong;
    // End of variables declaration//GEN-END:variables
public void addToPanelAccMana(List<Phong> listP) {
        Font font = new Font("SansSerif", Font.BOLD, 12);

        pnl_showlistPhong.removeAll();
        for (int i = 0; i < listP.size(); i += 1) {
            pnl_showlistPhong.setLayout(new GridLayout(listP.size() / 2 + 1, 2));
            try {
                // panel
                JPanel pnl = new JPanel();
                pnl.setLayout(new GridLayout(1, 2));

                // Add Id, name, Role
                JPanel pnlInfo = new JPanel();
                //  pnlInfo.setBackground(new Color(255, 255, 255));
                JLabel SoPhong = new JLabel("Số Phòng: " + listP.get(i).getSoPhong());
                JLabel loaiPhong = new JLabel("Loại Phòng: " + listP.get(i).getMaLoaiPhong());

                JLabel trangThai = new JLabel("Trạng thái: " + listP.get(i).getTrangthai());
                JLabel DatPhong = new JLabel();

                Phong epl = listP.get(i);
                PhieuDangKi pdk2 = pdkdao2.selectebySP(listP.get(i).getSoPhong());
                PhieuDangKi pdkCTT = pdkdao2.selectebySP_FalseTTHoaDOn(listP.get(i).getSoPhong());

                if (listP.get(i).getTrangthai() == null) {
                    pnlInfo.setBackground(Color.decode("#00CD00"));

                    pnl.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mousePressed(MouseEvent e) {
                            if (e.getClickCount() == 2 && !e.isConsumed()) {
                                frm_PhieuDangKy npl = new frm_PhieuDangKy();
                                npl.setVisible(true);

                                npl.setForm(epl);

                            }
                        }
                    });

                } else {
                    pnlInfo.setBackground(Color.decode("#FF4500"));

                    int index = i;
                    pnl.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mousePressed(MouseEvent e) {
                            if (e.getClickCount() == 2 && !e.isConsumed()) {
                                
                                //PhieuDangKi pdk2 = pdkdao2.selectebySP(listP.get(index).getSoPhong());
                                if(pdkCTT.getTinhTrangCho()==0){
                                frm_ChitietPhong npl = new frm_ChitietPhong();
                                npl.setVisible(true);
//                               npl.setForm(epl, pdk2);
                                frm_ChitietPhong.instance.setForm(epl, pdkCTT);
                                }
                            }
                        }
                    });

                }

                // Set font
                //   pnlInfo.setBorder(BorderFactory.createLineBorder(Color.yellow));
                SoPhong.setFont(new Font("SansSerif", Font.BOLD, 16));
                loaiPhong.setFont(font);
                trangThai.setFont(font);

                SoPhong.setForeground(Color.decode("#F5DEB3"));

                // set center lable in panel
                loaiPhong.setHorizontalAlignment(JLabel.CENTER);
                SoPhong.setHorizontalAlignment(JLabel.CENTER);
                trangThai.setHorizontalAlignment(JLabel.CENTER);

                // Add Id, name, role to panel
                pnlInfo.setLayout(new GridLayout(3, 1));
                pnlInfo.add(SoPhong);
                pnlInfo.add(loaiPhong);
                pnlInfo.add(trangThai);

          
                // Add property for panel
                pnl.add(pnlInfo);

              
                pnl.setBorder(BorderFactory.createLineBorder(new Color(150, 196, 200), 7));

                // Add event show form edit when click on panel
                // Add panel to panel Parent
                pnl_showlistPhong.add(pnl);
            } catch (Exception e) {
            }
        }
        pnl_showlistPhong.revalidate();
        pnl_showlistPhong.repaint();
    }

}
