/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mypackage.UI;

import com.qlks3tl.DAO.HoaDonDAO;
import com.qlks3tl.DAO.ThongKeDAO;
import com.qlks3tl.Model.PhieuDangKi;
import com.qlks3tl.utils.formatt;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class pnl_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form pnl_ThongKe
     */
    public pnl_ThongKe() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbo_ThongKe_Thang = new javax.swing.JComboBox<>();
        cbo_ThongKe_Nam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ThongKe_ThongKe = new javax.swing.JTable();
        lbl_ThongKe_TongTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(150, 196, 200));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(168, 222, 247)));
        setPreferredSize(new java.awt.Dimension(908, 683));

        jPanel1.setBackground(new java.awt.Color(150, 196, 200));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("THỐNG KÊ DOANH THU");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        cbo_ThongKe_Thang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbo_ThongKe_Thang.setForeground(new java.awt.Color(102, 0, 255));
        cbo_ThongKe_Thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ThongKe_ThangActionPerformed(evt);
            }
        });

        cbo_ThongKe_Nam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbo_ThongKe_Nam.setForeground(new java.awt.Color(204, 0, 204));
        cbo_ThongKe_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ThongKe_NamActionPerformed(evt);
            }
        });

        tbl_ThongKe_ThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 222, 247), 3));
        tbl_ThongKe_ThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_ThongKe_ThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên KH", "CMND", "SDT", "Loại Phòng", "Số Phòng", "Số Tiền"
            }
        ));
        tbl_ThongKe_ThongKe.setGridColor(new java.awt.Color(150, 196, 200));
        tbl_ThongKe_ThongKe.setRowHeight(27);
        tbl_ThongKe_ThongKe.setRowMargin(1);
        jScrollPane1.setViewportView(tbl_ThongKe_ThongKe);

        lbl_ThongKe_TongTien.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ThongKe_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_ThongKe_TongTien.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ThongKe_TongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ThongKe_TongTien.setText("Tổng Tiền");
        lbl_ThongKe_TongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbo_ThongKe_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cbo_ThongKe_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ThongKe_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_ThongKe_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_ThongKe_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(lbl_ThongKe_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_ThongKe_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ThongKe_NamActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThuNam();
    }//GEN-LAST:event_cbo_ThongKe_NamActionPerformed

    private void cbo_ThongKe_ThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ThongKe_ThangActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThuThang();
    }//GEN-LAST:event_cbo_ThongKe_ThangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_ThongKe_Nam;
    private javax.swing.JComboBox<String> cbo_ThongKe_Thang;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ThongKe_TongTien;
    private javax.swing.JTable tbl_ThongKe_ThongKe;
    // End of variables declaration//GEN-END:variables

    HoaDonDAO hddao = new HoaDonDAO();
    void fillComboBoxTheoNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_ThongKe_Nam.getModel();
        model.removeAllElements();

        List<Integer> list = hddao.selectYears();
        for (Integer year : list) {
            model.addElement(year);
        }
    } 
    void fillComboBoxTheoThang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_ThongKe_Thang.getModel();
        model.removeAllElements();

        List<Integer> list = hddao.selectMonth();
        for (Integer month : list) {
            model.addElement(month);
        }
    } 
    
    void init(){
        fillComboBoxTheoNam();
        fillComboBoxTheoThang();
        designTable();
    }
    ThongKeDAO tkdao= new ThongKeDAO();
    void fillTableDoanhThuNam() {
        PhieuDangKi lt = new PhieuDangKi();
        DefaultTableModel model = (DefaultTableModel) tbl_ThongKe_ThongKe.getModel();
        model.setRowCount(0);
        int nam = (Integer) cbo_ThongKe_Nam.getSelectedItem();
        List<Object[]> list = tkdao.getDoanhThuNam(nam);
        double tong = 0.0;
        for (Object[] row : list) {
            Object[] r = {row[0], row[1], row[2], row[3],row[4],(double)row[5]+"00 VNĐ"};
            model.addRow(r);
            tong += (double) row[5];
        }
        lbl_ThongKe_TongTien.setText(tong+"00 VNĐ");
    }

    void fillTableDoanhThuThang() {
        PhieuDangKi lt = new PhieuDangKi();
        DefaultTableModel model = (DefaultTableModel) tbl_ThongKe_ThongKe.getModel();
        model.setRowCount(0);
        int Thang = (Integer) cbo_ThongKe_Thang.getSelectedItem();
        int nam = (Integer) cbo_ThongKe_Nam.getSelectedItem();
        List<Object[]> list = tkdao.getDoanhThuThang(Thang, nam);
        double tong = 0.0;
        for (Object[] row : list) {
            Object[] r = {row[0], row[1], row[2], row[3],row[4],((double)row[5]+"00 VNĐ")};
            model.addRow(r);
            tong += (double) row[5];
        }
        lbl_ThongKe_TongTien.setText(tong+"00 VNĐ");

    }
     void designTable() {        
        tbl_ThongKe_ThongKe.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        tbl_ThongKe_ThongKe.getTableHeader().setForeground(Color.BLACK);
       
      
    }
}
