/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.UI;

import com.qlks3tl.DAO.PhieuDangKiDAO;
import com.qlks3tl.DAO.PhongDAO;
import com.qlks3tl.Model.PhieuDangKi;
import com.qlks3tl.Model.Phong;
import com.qlks3tl.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class pnl_Dsphong extends javax.swing.JPanel {

    /**
     * Creates new form frm_Dsphogn
     */
    public pnl_Dsphong() {
        initComponents();
        init();
    }
    
    void init() {
        initComponents();
        this.fillTable();
        designTable();
        
    }
     
    int row = -1;
    PhongDAO dao = new PhongDAO();
    PhieuDangKiDAO daopdk = new  PhieuDangKiDAO();
    
    void fillTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_DSPhong_DSPhong.getModel();
        model.setRowCount(0);
        
        try{
            List<Phong> list = dao.selectAll();// Lấy tất cả dữ liệu từ SQL 
            for(Phong p : list){
                Object[] row ={
                    p.getSoPhong(),p.getMaLoaiPhong(),
                    p.getGiaPhong_Ngay(),p.getGiaPhong_Gio(), p.getTrangthai()
                };
                model.addRow(row);
            }
        }
        catch(Exception e){
            MsgBox.alert(this,"Lỗi truy vấn dữ liệu");
        }
    }
    
    public Phong edit(){
        Phong p = new Phong();
        if (row != -1) {
            String SoPhong = (String) tbl_DSPhong_DSPhong.getValueAt(this.row, 0);
            tbl_DSPhong_DSPhong.setRowSelectionInterval(row, row);
            p = dao.selectebyID(SoPhong);
        }
       return p;
    }
    
     public PhieuDangKi editpdk(){
        PhieuDangKi pdka = new PhieuDangKi();
        if (row != -1) {
            String SoPhong = (String) tbl_DSPhong_DSPhong.getValueAt(this.row, 1);
            tbl_DSPhong_DSPhong.setRowSelectionInterval(row, row);
            pdka = daopdk.selectebySP(SoPhong);
        }
       return pdka;
    }
      
      
     private void timkiem(){
         
         DefaultTableModel model = (DefaultTableModel) tbl_DSPhong_DSPhong.getModel();
         model.setRowCount(0);
         
         String keyword = txt_DSPhong_timKiem.getText();
         List<Phong> list = dao.search(keyword);
         for(Phong dsp : list){
           model.addRow(new Object[]{
             
            dsp.getSoPhong(),
            dsp.getMaLoaiPhong(),
            dsp.getCMND(),
            dsp.getGiaPhong_Ngay(),
            dsp.getGiaPhong_Gio(),
            dsp.getTrangthai()
         });
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSPhong_DSPhong = new javax.swing.JTable();
        txt_DSPhong_timKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(150, 196, 200));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(168, 222, 247)));
        setPreferredSize(new java.awt.Dimension(908, 683));

        jPanel1.setBackground(new java.awt.Color(150, 196, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(908, 744));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("DANH SÁCH PHÒNG");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        tbl_DSPhong_DSPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 222, 247), 4));
        tbl_DSPhong_DSPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_DSPhong_DSPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số phòng", "Mã loại phòng", "Giá Phòng_Ngày", "Giá Phòng_Giờ"
            }
        ));
        tbl_DSPhong_DSPhong.setFocusable(false);
        tbl_DSPhong_DSPhong.setGridColor(new java.awt.Color(150, 196, 200));
        tbl_DSPhong_DSPhong.setRowHeight(30);
        tbl_DSPhong_DSPhong.setRowMargin(3);
        tbl_DSPhong_DSPhong.setSelectionBackground(new java.awt.Color(150, 196, 200));
        tbl_DSPhong_DSPhong.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                tbl_DSPhong_DSPhongComponentRemoved(evt);
            }
        });
        tbl_DSPhong_DSPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DSPhong_DSPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DSPhong_DSPhong);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Danh Sách Chờ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_DSPhong_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DSPhong_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DSPhong_DSPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DSPhong_DSPhongMouseClicked
    
        if (evt.getClickCount() == 1) {
            Phong p = new Phong();
            PhieuDangKi pdka = new PhieuDangKi();
            this.row = tbl_DSPhong_DSPhong.getSelectedRow();
            p = this.edit();
            pdka = this.editpdk();
            frm_CapNhat cn = new frm_CapNhat();
            cn.setVisible(true);
            cn.setForm(p);
            cn.fillTable(pdka);
        }  
    }//GEN-LAST:event_tbl_DSPhong_DSPhongMouseClicked

    private void tbl_DSPhong_DSPhongComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tbl_DSPhong_DSPhongComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_DSPhong_DSPhongComponentRemoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DanhSachPhongCho dsc= new DanhSachPhongCho();
        dsc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_DSPhong_DSPhong;
    private javax.swing.JTextField txt_DSPhong_timKiem;
    // End of variables declaration//GEN-END:variables
 void designTable() {        
        tbl_DSPhong_DSPhong.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        tbl_DSPhong_DSPhong.getTableHeader().setForeground(Color.BLACK);
       
      
    }
}
