/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.UI;

import com.qlks3tl.DAO.HoaDonDAO;
import com.qlks3tl.Model.HoaDon;
import com.qlks3tl.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class pnl_HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form frm_Dsphogn
     */
    public pnl_HoaDon() {
        initComponents();
        init();
      

    }
    void init(){
        initComponents();
        this.fillTable();
        designTable();
    }
    
    HoaDonDAO dao = new HoaDonDAO();
    int row = -1;
    
    void fillTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_HoaDon_HoaDon.getModel();
        model.setRowCount(0);
        
        try{
            List<HoaDon> list = dao.selectAll();// Lấy tất cả dữ liệu từ SQL 
            for(HoaDon hd : list){
                Object[] row ={
                    hd.getMaHD(),hd.getMaNV(),hd.getMaPDK(),hd.getCMND(),
                    hd.getSoPhong(),hd.getGhiChu(),hd.getNgayTao(),hd.getTongTien()
                };
                   model.addRow(row);
            }
        }
        catch(Exception e){
            MsgBox.alert(this,"Lỗi truy vấn dữ liệu" );
        }
    }
    public HoaDon edit(){
        HoaDon hd = new HoaDon();
        if (row != -1) {
            String maHD = (String) tbl_HoaDon_HoaDon.getValueAt(this.row, 0);
            tbl_HoaDon_HoaDon.setRowSelectionInterval(row, row);
            hd = dao.selectebyID(maHD);
        }
        System.out.println(hd);
       return hd;
    }
    private void timkiem(){
         
         DefaultTableModel model = (DefaultTableModel) tbl_HoaDon_HoaDon.getModel();
         model.setRowCount(0);
         
         String keyword = txt_HoaDon_timKiem.getText();
         List<HoaDon> list = dao.search(keyword);
         for(HoaDon hds : list){
            model.addRow(new Object[]{
             
                hds.getMaHD(),
                hds.getMaNV(),
                hds.getMaPDK(),
                hds.getSoPhong(),
                hds.getGhiChu(),
                hds.getNgayTao(),
                hds.getTongTien()
                
            
           
         });
         }
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_HoaDon_timKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon_HoaDon = new javax.swing.JTable();
        txt_HD_timkiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(150, 196, 200));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(168, 222, 247)));
        setPreferredSize(new java.awt.Dimension(908, 743));

        jPanel1.setBackground(new java.awt.Color(150, 196, 200));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 99, 198));
        jLabel7.setText("HÓA ĐƠN");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);

        jPanel2.setBackground(new java.awt.Color(150, 196, 200));

        tbl_HoaDon_HoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 222, 247), 4));
        tbl_HoaDon_HoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_HoaDon_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã Nhân Viên", "Mã phiếu DK", "CMND", "Số phòng", "Ghi chú", "Ngày Tạo", "Tổng Tiền"
            }
        ));
        tbl_HoaDon_HoaDon.setGridColor(new java.awt.Color(150, 196, 200));
        tbl_HoaDon_HoaDon.setRowHeight(27);
        tbl_HoaDon_HoaDon.setRowMargin(2);
        tbl_HoaDon_HoaDon.setSelectionBackground(new java.awt.Color(150, 196, 200));
        tbl_HoaDon_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDon_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDon_HoaDon);

        txt_HD_timkiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_HD_timkiem.setForeground(new java.awt.Color(51, 51, 255));
        txt_HD_timkiem.setText("Tìm kiếm");
        txt_HD_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HD_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_HD_timkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_HoaDon_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_HoaDon_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txt_HD_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_HoaDon_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDon_HoaDonMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            frm_ChiTietHoaDon cthd = new frm_ChiTietHoaDon();
            cthd.setVisible(true);
            this.row = tbl_HoaDon_HoaDon.getSelectedRow();
            cthd.setForm(this.edit());
        }
    }//GEN-LAST:event_tbl_HoaDon_HoaDonMouseClicked

    private void txt_HD_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HD_timkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_txt_HD_timkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_HoaDon_HoaDon;
    private javax.swing.JButton txt_HD_timkiem;
    private javax.swing.JTextField txt_HoaDon_timKiem;
    // End of variables declaration//GEN-END:variables

     void designTable() {        
        tbl_HoaDon_HoaDon.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        tbl_HoaDon_HoaDon.getTableHeader().setForeground(Color.BLACK);
       
      
    }
}
